packages:
  - 'packages/*'
catalog:
  '@antfu/eslint-config': ^4.13.1
  '@inkart/temps': 0.0.2
  '@rollup/plugin-json': ^6.1.0
  '@types/node': ^20.8.10
  '@types/prompts': ^2.4.9
  cac: ^6.7.14
  chalk: ^5.4.1
  eslint: ^9.27.0
  eslint-plugin-format: ^1.0.1
  prompts: ^2.4.2
  rollup: ^4.41.0
  rollup-plugin-esbuild: ^6.2.1
  ts-node: ^10.9.1
  typescript: ^5.2.2
